made handshake more robust
HWXLR8/echo-chan-firmware pull request #7
Opened 2022-08-04 07:21 UTC by ericjtaylor

closes #1 closes #2 closes #3

2022-08-10 21:31 UTC, HWXLR8 requested changes
minor issues, looks good otherwise

2022-08-10 21:31 UTC, HWXLR8 commented on firmware.c
> +    if ((!HANDSHAKED && (usb_serial_get_control() & USB_SERIAL_DTR))) {
is there a reason for the parens around `(usb_serial_get_control() & USB_SERIAL_DTR)`? also why the bitwise & instead of logical && ?

2022-08-10 21:31 UTC, HWXLR8 commented on firmware.c
> +    else if (!(usb_serial_get_control() & USB_SERIAL_DTR)) {
same comment, & vs &&

2022-08-10 21:31 UTC, HWXLR8 commented on firmware.c
> +    if (PINA_NEW != PINA_OLD || PINB_NEW != PINB_OLD || PINC_NEW != PINC_OLD){
you missed a space after the ending paren causing git to think this line changed. you should run `git diff` before you commit to visually inspect for what you actually changed. I find this to be a good way to catch accidental extra lines or leftover debug code. you can also try using a program to enforce a certain style. `clang-format` provided by the clang compiler is a great one for c/c++.

2022-08-11 15:30 UTC, ericjtaylor commented on firmware.c
> +    if (PINA_NEW != PINA_OLD || PINB_NEW != PINB_OLD || PINC_NEW != PINC_OLD){
fwiw i do check diffs every time but must have missed this line.

2022-08-11 15:30 UTC, ericjtaylor commented on firmware.c
> +    if ((!HANDSHAKED && (usb_serial_get_control() & USB_SERIAL_DTR))) {
good catch, works as is but i will clean it up and resubmit

2022-08-11 15:30 UTC, ericjtaylor commented on firmware.c
> +    else if (!(usb_serial_get_control() & USB_SERIAL_DTR)) {
ditto

2022-08-11 22:29 UTC, ericjtaylor commented on firmware.c
> +    if ((!HANDSHAKED && (usb_serial_get_control() & USB_SERIAL_DTR))) {
rereading the code `usb_serial_get_control()` returns a bitfield and `USB_SERIAL_DTR` defines which bit in the bitfield is the DTR flag. so the parentheses are making the order of operations explicit and segmenting out this bitwise operation.

2022-08-11 22:36 UTC, ericjtaylor commented
all changes complete. please see comments and revised diff

2022-08-12 23:01 UTC, HWXLR8 commented
thank you

2022-08-12 23:01 UTC, merged